#ifndef STORAGE_H
#define STORAGE_H


#define STORAGE_TAG "STORAGE"
// #define STORAGE_USE_HARDWARE
#define STORAGE_USE_EMULATION


// #define STORAGE_SDCARD_ENABLED 

#define STORAGE_FLOWMETER_PROFILE_ADDRESS 0
// #define STORAGE_PUBLISHER_ENABLE_ADDRESS 1
#define STORAGE_PUBLISHER_SENSOR_ADDRESS 2
//#define STORAGE_PUBLISHER_DELAY_ADDRESS 3
#define STORAGE_FIRST_RUN_INIT_ADDRESS 4 // 1 byte

#define STORAGE_FM_COUNTER_ADDRESS_1 5 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_2 13 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_3 21 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_4 29  // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_5 37 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_6 45 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_7 53 // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_8 61  // 8 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_1 69 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_2 73 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_3 77 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_4 81 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_5 85 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_6 89 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_7 93 // 4 bytes
#define STORAGE_FM_COUNTER_ADDRESS_COUNTER_8 97 // 4 bytes

// #define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS 101 // 8 bytes
// #define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS 109 // 4 bytes



#define STORAGE_FLOWMETER_PIN_ADDRESS 117 // 1 byte

#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_1 118 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_2 122 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_3 126 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_4 130 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_5 134 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_6 138 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_7 142 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_8 146 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_1 150 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_2 154 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_3 158 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_4 162 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_5 166 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_6 170 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_7 174 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_START_ADDRESS_COUNTER_8 178 // 4 bytes

#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_1 182 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_2 186 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_3 190 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_4 194 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_5 198 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_6 202 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_7 206 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_8 210 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_1 214 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_2 218 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_3 222 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_4 226 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_5 230 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_6 234 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_7 238 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_END_ADDRESS_COUNTER_8 242 // 4 bytes

#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_1 246 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_2 254 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_3 262 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_4 270 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_5 278 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_6 286 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_7 294 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_8 302 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_1 310 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_2 314 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_3 318 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_4 322 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_5 326 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_6 330 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_7 334 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_DATA_ADDRESS_COUNTER_8 338 // 4 bytes

#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_1 342 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_2 346 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_3 350 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_4 354 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_5 358 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_6 362 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_7 366 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_8 370 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_1 374 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_2 378 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_3 382 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_4 386 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_5 390 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_6 394 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_7 398 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_ADDRESS_COUNTER_8 402 // 4 bytes

#define STORAGE_FM_ENABLED_ADDRESS_1 406 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_2 407 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_3 408 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_4 409 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_5 410 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_6 411 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_7 412 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_8 413 // 1 byte
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_1 414 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_2 418 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_3 422 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_4 426 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_5 430 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_6 434 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_7 438 // 4 bytes
#define STORAGE_FM_ENABLED_ADDRESS_COUNTER_8 442 // 4 bytes

#define STORAGE_FM_PIN_NUMBER_ADDRESS_1 446 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_2 447 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_3 448 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_4 449 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_5 450 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_6 451 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_7 452 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_8 453 // 1 byte
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_1 454 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_2 458 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_3 462 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_4 466 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_5 470 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_6 474 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_7 478 // 4 bytes
#define STORAGE_FM_PIN_NUMBER_ADDRESS_COUNTER_8 482 // 4 bytes


#define STORAGE_TIME_UTC_OFFSET_ADDRESS_1 486 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_2 488 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_3 490 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_4 492 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_5 494 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_6 496 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_7 498 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_8 500 // 2 byte
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_1 502 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_2 506 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_3 510 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_4 514 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_5 518 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_6 522 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_7 526 // 4 bytes
#define STORAGE_TIME_UTC_OFFSET_ADDRESS_COUNTER_8 530 // 4 bytes

#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_1 534 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_2 538 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_3 542 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_4 546 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_5 550 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_6 554 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_8 558 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_0 662 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_1 666 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_2 670 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_3 674 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_4 678 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_5 682 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_6 686 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_7 690 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_8 694 // 4 bytes


#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_1 698 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_2 706 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_3 714 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_4 722 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_5 730 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_6 738 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_7 746 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_8 754 // 8 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_1 762 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_2 766 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_3 770 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_4 774 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_5 778 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_6 782 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_7 786 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_DATA_ADDRESS_COUNTER_8 780 // 4 bytes

#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_1 784 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_2 788 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_3 802 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_4 806 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_5 810 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_6 814 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_7 818 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_8 822 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_1 826 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_2 830 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_3 834 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_4 838 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_5 842 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_6 846 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_7 850 // 4 bytes
#define STORAGE_FM_COUNTER_PREVIOUS_INTERVAL_TIMESTAMP_END_ADDRESS_COUNTER_8 854 // 4 bytes


#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_1 858 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_2 866 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_3 874 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_4 882 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_5 890 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_6 898 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_7 906 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_8 914 // 8 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_1 922 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_2 926 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_3 930 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_4 934 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_5 938 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_6 942 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_7 946 // 4 bytes
#define STORAGE_FM_COUNTER_INTERVAL_TOP_DATA_ADDRESS_COUNTER_8 950 // 4 bytes

#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_1 954 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_2 956 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_3 958 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_4 960 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_5 962 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_6 964 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_7 966 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_8 968 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_1 970 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_2 974 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_3 978 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_4 982 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_5 986 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_6 990 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_7 994 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_TIME_ADDRESS_COUNTER_8 998 // 4 bytes

#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_1 1002 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_2 1004 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_3 1006 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_4 1008 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_5 1010 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_6 1012 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_7 1014 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_8 1016 // 2 byte
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_1 1018 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_2 1022 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_3 1026 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_4 1030 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_5 1034 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_6 1038 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_7 1042 // 4 bytes
#define STORAGE_FM_INTERVAL_CALCULATION_VALUE_ADDRESS_COUNTER_8 1046 // 4 bytes


#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_1 1050 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_2 1051 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_3 1052 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_4 1053 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_5 1054 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_6 1055 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_7 1056 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_8 1057 // 1 byte
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_1 1058 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_2 1062 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_3 1066 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_4 1070 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_5 1074 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_6 1078 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_7 1082 // 4 bytes
#define STORAGE_FM_CALC_ALGO_ENABLED_ADDRESS_COUNTER_8 1086 // 4 bytes

#define STORAGE_PUBLISHER_ENABLE_ADDRESS_1 1090 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_2 1094 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_3 1098 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_4 1102 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_5 1106 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_6 1110 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_7 1114 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_8 1118 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_1 1122 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_2 1126 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_3 1130 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_4 1134 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_5 1138 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_6 1142 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_7 1146 // 4 bytes
#define STORAGE_PUBLISHER_ENABLE_ADDRESS_COUNTER_8 1150 // 4 bytes

#define STORAGE_PUBLISHER_DELAY_ADDRESS_1 1154 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_2 1158 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_3 1162 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_4 1166 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_5 1170 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_6 1174 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_7 1178 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_8 1182 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_1 1186 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_2 1190 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_3 1194 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_4 1198 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_5 1202 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_6 1206 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_7 1210 // 4 bytes
#define STORAGE_PUBLISHER_DELAY_ADDRESS_COUNTER_8 1214 // 4 bytes

#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_1 1218 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_2 1222 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_3 1226 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_4 1230 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_5 1234 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_6 1238 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_7 1242 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_8 1246 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_1 1250 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_2 1256 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_3 1260 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_4 1264 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_5 1268 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_6 1272 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_7 1276 // 4 bytes
#define STORAGE_PUBLISHER_NEXT_TIMESTAMP_ADDRESS_COUNTER_8 1280 // 4 bytes

#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_1 1284 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_2 1288 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_3 1292 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_4 1296 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_5 1300 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_6 1304 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_7 1308 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_8 1312 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_1 1316 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_2 1320 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_3 1324 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_4 1328 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_5 1332 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_6 1336 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_7 1340 // 4 bytes
#define STORAGE_PUBLISHER_LAST_TIMESTAMP_ADDRESS_COUNTER_8 1344 // 4 bytes



#define STORAGE_PUBLISHER_ENABLED_ADDRESS_1 1348 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_2 1349 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_3 1350 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_4 1351 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_5 1352 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_6 1353 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_7 1354 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_8 1355 // 1 byte
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_1 1356 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_2 1360 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_3 1364 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_4 1368 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_5 1372 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_6 1376 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_7 1380 // 4 bytes
#define STORAGE_PUBLISHER_ENABLED_ADDRESS_COUNTER_8 1384 // 4 bytes




// four 32 bits variables for operation settings
#define STORAGE_OPERATION_SETTINGS_ADDRESS_1 1388 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_2 1392 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_3 1396 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_4 1400 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_5 1404 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_6 1408 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_7 1412 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_8 1416 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_1 1420 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_2 1424 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_3 1428 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_4 1432 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_5 1436 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_6 1440 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_7 1444 // 4 bytes
#define STORAGE_OPERATION_SETTINGS_ADDRESS_COUNTER_8 1448 // 4 bytes

#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_1 1452 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_2 1456 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_3 1460 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_4 1464 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_5 1468 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_6 1472 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_7 1476 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_8 1480 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_1 1484 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_2 1488 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_3 1492 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_4 1496 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_5 1500 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_6 1504 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_7 1508 // 4 bytes
#define STORAGE_OPERATION_SENSOR_DATA_SETTINGS_ADDRESS_COUNTER_8 1512 // 4 bytes


#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_1 1516 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_2 1520 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_3 1524 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_4 1528 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_5 1532 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_6 1536 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_7 1540 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_8 1544 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_1 1548 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_2 1552 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_3 1556 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_4 1560 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_5 1564 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_6 1568 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_7 1572 // 4 bytes
#define STORAGE_OPERATION_NUMBERS_SETTINGS_ADDRESS_COUNTER_8 1576 // 4 bytes

#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_1 1580 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_2 1584 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_3 1588 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_4 1592 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_5 1596 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_6 1600 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_7 1604 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_8 1608 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_1 1612 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_2 1616 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_3 1620 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_4 1624 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_5 1628 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_6 1632 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_7 1636 // 4 bytes
#define STORAGE_OPERATION_TIMINGS_SETTINGS_ADDRESS_COUNTER_8 1640 // 4 bytes


#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_1 1644 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_2 1648 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_3 1652 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_4 1656 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_5 1660 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_6 1664 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_7 1668 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_8 1672 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_1 1676 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_2 1680 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_3 1684 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_4 1688 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_5 1692 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_6 1696 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_7 1700 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_ADDRESS_COUNTER_8 1704 // 4 bytes

#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_1 1708 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_2 1712 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_3 1716 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_4 1720 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_5 1724 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_6 1728 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_7 1732 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_8 1736 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_1 1740 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_2 1744 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_3 1748 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_4 1752 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_5 1756 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_6 1760 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_7 1764 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_HIGH_VALUE_ADDRESS_COUNTER_8 1768 // 4 bytes

#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_1 1772 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_2 1776 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_3 1780 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_4 1784 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_5 1788 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_6 1792 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_7 1796 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_8 1800 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_1 1804 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_2 1808 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_3 1812 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_4 1816 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_5 1820 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_6 1824 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_7 1828 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_LOW_VALUE_ADDRESS_COUNTER_8 1832 // 4 bytes

#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_1 1836 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_2 1840 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_3 1844 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_4 1848 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_5 1852 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_6 1856 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_7 1860 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_8 1864 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_1 1868 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_2 1872 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_3 1876 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_4 1880 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_5 1884 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_6 1888 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_7 1892 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_VARIANCE_ADDRESS_COUNTER_8 1896 // 4 bytes

#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_1 1900 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_2 1904 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_3 1908 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_4 1912 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_5 1916 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_6 1920 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_7 1924 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_8 1928 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_1 1932 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_2 1936 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_3 1940 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_4 1944 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_5 1948 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_6 1952 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_7 1956 // 4 bytes
#define STORAGE_AMBIENT_LIGHT_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_8 1960 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_1 1964 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_2 1968 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_3 1972 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_4 1976 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_5 1980 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_6 1984 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_7 1988 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_8 1992 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_1 1996 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_2 2000 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_3 2004 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_4 2008 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_5 2012 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_6 2016 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_7 2020 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_ADDRESS_COUNTER_8 2024 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_1 2028 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_2 2032 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_3 2036 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_4 2040 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_5 2044 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_6 2048 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_7 2052 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_8 2056 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_1 2060 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_2 2064 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_3 2068 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_4 2072 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_5 2076 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_6 2080 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_7 2084 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_HIGH_ADDRESS_COUNTER_8 2088 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_1 2092 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_2 2096 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_3 2100 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_4 2104 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_5 2108 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_6 2112 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_7 2116 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_8 2120 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_1 2124 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_2 2128 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_3 2132 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_4 2136 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_5 2140 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_6 2144 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_7 2148 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_TEMPERATURE_LOW_ADDRESS_COUNTER_8 2152 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_1 2156 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_2 2160 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_3 2164 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_4 2168 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_5 2172 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_6 2176 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_7 2180 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_8 2184 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_1 2188 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_2 2192 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_3 2196 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_4 2200 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_5 2204 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_6 2208 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_7 2212 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_HIGH_ADDRESS_COUNTER_8 2216 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_1 2220 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_2 2224 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_3 2228 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_4 2232 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_5 2236 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_6 2240 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_7 2244 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_8 2248 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_1 2252 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_2 2256 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_3 2260 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_4 2264 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_5 2268 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_6 2272 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_7 2276 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_HUMIDITY_LOW_ADDRESS_COUNTER_8 2280 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_1 2284 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_2 2288 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_3 2292 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_4 2296 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_5 2300 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_6 2304 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_7 2308 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_8 2312 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_1 2316 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_2 2320 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_3 2324 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_4 2328 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_5 2332 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_6 2336 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_7 2340 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_PERSISTENCE_ADDRESS_COUNTER_8 2344 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_1 2348 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_2 2352 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_3 2356 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_4 2360 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_5 2364 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_6 2368 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_7 2372 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_8 2376 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_1 2380 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_2 2384 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_3 2388 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_4 2392 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_5 2396 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_6 2400 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_7 2404 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_VARIANCE_ADDRESS_COUNTER_8 2408 // 4 bytes

#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_1 2412 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_2 2416 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_3 2420 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_4 2424 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_5 2428 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_6 2432 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_7 2436 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_8 2440 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_1 2444 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_2 2448 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_3 2452 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_4 2456 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_5 2460 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_6 2464 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_7 2468 // 4 bytes
#define STORAGE_TEMPERATURE_HUMDITY_SETTINGS_MEASUREMENT_ADDRESS_COUNTER_8 2472 // 4 bytes


#define STORAGE_INERTIAL_SETTINGS_ADDRESS_1 2476 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_2 2480 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_3 2484 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_4 2488 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_5 2492 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_6 2496 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_7 2500 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_8 2504 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_1 2508 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_2 2512 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_3 2516 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_4 2520 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_5 2524 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_6 2528 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_7 2532 // 4 bytes
#define STORAGE_INERTIAL_SETTINGS_ADDRESS_COUNTER_8 2536 // 4 bytes

#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_1 2540 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_2 2544 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_3 2548 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_4 2552 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_5 2556 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_6 2560 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_7 2564 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_8 2568 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_1 2572 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_2 2576 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_3 2580 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_4 2584 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_5 2588 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_6 2592 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_7 2596 // 4 bytes
#define STORAGE_INERTIAL_ACCELEROMETER_SETTINGS_ADDRESS_COUNTER_8 2600 // 4 bytes

#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_1 2604 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_2 2608 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_3 2612 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_4 2616 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_5 2620 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_6 2624 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_7 2628 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_8 2632 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_1 2636 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_2 2640 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_3 2644 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_4 2648 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_5 2652 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_6 2656 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_7 2660 // 4 bytes
#define STORAGE_INERTIAL_GYRO_SETTINGS_ADDRESS_COUNTER_8 2664 // 4 bytes

#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_1 2668 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_2 2672 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_3 2676 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_4 2680 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_5 2684 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_6 2688 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_7 2692 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_8 2696 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_1 2700 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_2 2704 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_3 2708 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_4 2712 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_5 2716 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_6 2720 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_7 2724 // 4 bytes
#define STORAGE_INERTIAL_TEMPERATURE_SETTINGS_ADDRESS_COUNTER_8 2728 // 4 bytes

#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_1 2732 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_2 2736 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_3 2740 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_4 2744 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_5 2748 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_6 2752 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_7 2756 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_8 2760 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_1 2764 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_2 2768 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_3 2772 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_4 2776 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_5 2780 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_6 2784 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_7 2788 // 4 bytes
#define STORAGE_INERTIAL_INTERRUPT_SETTINGS_ADDRESS_COUNTER_8 2792 // 4 bytes

#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_1 2796 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_2 2800 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_3 2804 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_4 2808 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_5 2812 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_6 2816 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_7 2820 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_8 2824 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_1 2828 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_2 2832 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_3 2836 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_4 2840 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_5 2844 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_6 2848 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_7 2852 // 4 bytes
#define STORAGE_INERTIAL_STEP_COUNTER_SETTINGS_ADDRESS_COUNTER_8 2856 // 4 bytes

#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_1 2860 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_2 2864 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_3 2868 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_4 2872 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_5 2876 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_6 2880 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_7 2884 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_8 2888 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_1 2892 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_2 2896 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_3 2900 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_4 2904 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_5 2908 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_6 2912 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_7 2916 // 4 bytes
#define STORAGE_INERTIAL_STATE_MACHINE_SETTINGS_ADDRESS_COUNTER_8 2920 // 4 bytes

#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_1 2924 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_2 2928 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_3 2932 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_4 2936 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_5 2940 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_6 2944 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_7 2948 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_8 2952 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_1 2956 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_2 2960 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_3 2964 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_4 2968 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_5 2972 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_6 2976 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_7 2980 // 4 bytes
#define STORAGE_INERTIAL_FREEFALL_SETTINGS_ADDRESS_COUNTER_8 2984 // 4 bytes

#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_1 2988 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_2 2992 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_3 2996 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_4 3000 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_5 3004 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_6 3008 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_7 3012 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_8 3016 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_1 3020 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_2 3024 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_3 3028 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_4 3032 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_5 3036 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_6 3040 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_7 3044 // 4 bytes
#define STORAGE_INERTIAL_SENSORHUB_SETTINGS_ADDRESS_COUNTER_8 3048 // 4 bytes




#define STORAGE_GNSS_SETTINGS_ADDRESS_1 3052 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_2 3056 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_3 3060 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_4 3064 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_5 3068 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_6 3072 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_7 3076 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_8 3080 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_1 3084 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_2 3088 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_3 3092 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_4 3096 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_5 3100 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_6 3104 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_7 3108 // 4 bytes
#define STORAGE_GNSS_SETTINGS_ADDRESS_COUNTER_8 3112 // 4 bytes

#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_1 3116 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_2 3120 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_3 3124 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_4 3128 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_5 3132 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_6 3136 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_7 3140 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_8 3144 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_1 3148 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_2 3152 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_3 3156 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_4 3160 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_5 3164 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_6 3168 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_7 3172 // 4 bytes
#define STORAGE_GNSS_INTERRUPT_SETTINGS_ADDRESS_COUNTER_8 3176 // 4 bytes

#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_1 3180 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_2 3184 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_3 3188 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_4 3192 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_5 3196 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_6 3200 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_7 3204 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_8 3208 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_1 3212 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_2 3216 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_3 3220 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_4 3224 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_5 3228 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_6 3232 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_7 3236 // 4 bytes
#define STORAGE_GNSS_GEO_SETTINGS_ADDRESS_COUNTER_8 3240 // 4 bytes

#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_1 3244 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_2 3248 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_3 3252 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_4 3256 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_5 3260 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_6 3264 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_7 3268 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_8 3272 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_1 3276 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_2 3280 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_3 3284 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_4 3288 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_5 3292 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_6 3296 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_7 3300 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_1_ADDRESS_COUNTER_8 3304 // 4 bytes

#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_1 3308 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_2 3312 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_3 3316 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_4 3320 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_5 3324 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_6 3328 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_7 3332 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_8 3336 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_1 3340 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_2 3344 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_3 3348 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_4 3352 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_5 3356 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_6 3360 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_7 3364 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_2_ADDRESS_COUNTER_8 3368 // 4 bytes

#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_1 3372 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_2 3376 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_3 3380 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_4 3384 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_5 3388 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_6 3392 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_7 3396 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_8 3400 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_1 3404 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_2 3408 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_3 3412 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_4 3416 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_5 3420 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_6 3424 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_7 3428 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_3_ADDRESS_COUNTER_8 3432 // 4 bytes

#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_1 3436 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_2 3440 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_3 3444 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_4 3448 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_5 3452 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_6 3456 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_7 3460 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_8 3464 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_1 3468 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_2 3472 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_3 3476 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_4 3480 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_5 3484 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_6 3488 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_7 3492 // 4 bytes
#define STORAGE_GNSS_GEO_POINT_4_ADDRESS_COUNTER_8 3496 // 4 bytes

int storage_write_zeroes();
int storage_init();

int storage_write_u8(uint32_t addr, uint8_t val);
int storage_write_u16(uint32_t addr, uint16_t val);
int storage_write_u32(uint32_t addr, uint32_t val);
int storage_write_u64(uint32_t addr, uint64_t val);
int storage_read_u8(uint32_t addr, uint8_t *val);
int storage_read_u16(uint32_t addr, uint16_t *val);
int storage_read_u32(uint32_t addr, uint32_t *val);
int storage_read_u64(uint32_t addr, uint64_t *val);
int storage_write_block(uint32_t addr, uint8_t *data, uint32_t data_size);
int storage_read_block(uint32_t addr, uint8_t *buff, uint32_t buff_size);

int storage_counter_write_u8(uint32_t addr, uint32_t counter_addr, uint8_t val);
int storage_counter_write_u16(uint32_t addr, uint32_t counter_addr, uint16_t val);
int storage_counter_write_u32(uint32_t addr, uint32_t counter_addr, uint32_t val);
int storage_counter_write_u64(uint32_t addr, uint32_t counter_addr, uint64_t val);
int storage_counter_read_u8(uint32_t addr, uint32_t counter_addr, uint8_t *val);
int storage_counter_read_u16(uint32_t addr, uint32_t counter_addr, uint16_t *val);
int storage_counter_read_u32(uint32_t addr, uint32_t counter_addr, uint32_t *val);
int storage_counter_read_u64(uint32_t addr, uint32_t counter_addr, uint64_t *val);

#endif